simulation_config:
  map_filename: "data_maps/single_voxel_x2_y4_z2.npy"
  map_resolution_cm: 10   # input file map voxel size (width/height/depth)
  initial_drone_position:
    x_cm: 25
    y_cm: 25
    height_cm: 25
  initial_angle_deg: 0     # 0=east, 90=south, 180=west, 270=north
  map_axes_offset:         # Turns (0,0,0) -> (x_offset,y_offset,height_offset)
    x_offset: 0
    y_offset: 0
    height_offset: 0
